spring:
  application.name: test-auth-system
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test_pass
  jpa:
    show-sql: true
  flyway:
    schemas: auth_system