spring:
  application.name: test-auth-system
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test_pass
  jpa:
    show-sql: true
  flyway:
    schemas: auth_system

password-generator:
  pbkdf2:
    iteration-count: 65536
    key-length: 512
    salt-length: 64

jwt:
  token:
    issuer: auth-system
    lifespan: 10m
    secret: vBfJh8HGEm1rbFQW50vOv5LpGoVlfV1gn4MPEnYlE7wJvlWuVc0H7iHkjC2O7wnziEdpkiEWwhuV9ls3fqL3hS75estTlkdNEEXK
